import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
//user imports
import moment from "moment";
import { ScrollArea } from "@mantine/core";
import { useState } from "react";

//placeholder data for timeline
const groups = [
  { id: 1, title: "group 1" },
  { id: 2, title: "group 2" },
  { id: 3, title: "group 3" },
  { id: 4, title: "group 4" },
  { id: 5, title: "group 5" },
  { id: 6, title: "group 6" },
  { id: 7, title: "group 7" },
];

const items = [
  {
    id: 1,
    group: 1,
    title: "item 1",
    start_time: moment(),
    end_time: moment().add(1, "hour"),
  },
  {
    id: 2,
    group: 2,
    title: "item 2",
    start_time: moment().add(-0.5, "hour"),
    end_time: moment().add(0.5, "hour"),
  },
  {
    id: 3,
    group: 1,
    title: "item 3",
    start_time: moment().add(2, "hour"),
    end_time: moment().add(3, "hour"),
  },
];

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col">
        <div className="flex w-full items-center justify-center bg-neutral-200 pt-6 text-2xl text-blue-500">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
        <ScrollArea className="min-w-screen">
          <div className="min-w-fit">
            <MonthSquare />
          </div>
        </ScrollArea>
      </main>
    </>
  );
};

//monthsquare shows 4 weekgrids
const MonthSquare: React.FC = () => {
  const [month, setMonth] = useState(moment());
  const [week, setWeek] = useState(moment().startOf("week"));
  return (
    <div className="flex flex-col">
      <h2>
        <span className="text-2xl"></span>
        <span className="text-2xl">{month.format("MMMM")}</span>
      </h2>
      <WeekGrid />
      <WeekGrid />
      <WeekGrid />
      <WeekGrid />
    </div>
  );
};

const WeekGrid: React.FC = () => {
  const length = 7;
  return (
    <div className="flex flex-row">
      {/* show 21 DaySquares */}
      {[...Array(length)].map((_, i) => (
        <DaySquare key={i} />
      ))}
    </div>
  );
};

const DaySquare: React.FC = () => {
  return (
    <div className="flex flex-col items-center justify-center">
      <div className="h-28 w-28 border-2 border-neutral-300 bg-neutral-500">
        <div className="text-center text-xs text-neutral-100">Day</div>
      </div>
    </div>
  );
};

export default Home;
